name    'martezr-exchange2013'
version '0.1.0'
source ''
author 'Martez Reed'
license ''
summary 'Puppet module to install Citrix Xendesktop 7'
description 'Puppet module to install Citrix Xendesktop 7'
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'SaizMaddali/puppet', '0.1.0'
